version: 2

run:
  # Timeout for analysis
  timeout: 5m

  # Include test files
  tests: true

formatters:
  enable:
    - gofmt         # Checks whether code was gofmt-ed
    - goimports     # Check import statements are formatted

linters:
  enable:
    # Default linters
    - errcheck      # Check for unchecked errors
    - govet         # Vet examines Go source code
    - ineffassign   # Detects ineffectual assignments
    - staticcheck   # Advanced Go linter (includes gosimple)
    - unused        # Checks for unused constants, variables, functions and types

    # Additional recommended linters
    - misspell      # Finds commonly misspelled English words
    - revive        # Fast, configurable, extensible, flexible, and beautiful linter for Go
    - gosec         # Inspects source code for security problems
    - gocritic      # Provides diagnostics that check for bugs, performance and style issues
    - gocyclo       # Computes cyclomatic complexity
    - dupl          # Code clone detection
    - exhaustive    # Check exhaustiveness of enum switch statements
    - copyloopvar   # Detects places where loop variables are copied
    - funlen        # Tool for detection of long functions
    - gocognit      # Computes cognitive complexity
    - goconst       # Finds repeated strings that could be constants
    - godot         # Check if comments end in a period
    - goprintffuncname # Checks that printf-like functions are named with f at the end
    - nolintlint    # Reports ill-formed or insufficient nolint directives
    - prealloc      # Finds slice declarations that could potentially be pre-allocated
    - predeclared   # Finds code that shadows predeclared identifiers
    - unconvert     # Removes unnecessary type conversions
    - unparam       # Reports unused function parameters
    - whitespace    # Detection of leading and trailing whitespace

formatters-settings:
  gofmt:
    # Simplify code
    simplify: true

  goimports:
    # Put imports beginning with prefix after 3rd-party packages
    local-prefixes: github.com/cangussu/monhang

linters-settings:
  errcheck:
    # Report about not checking of errors in type assertions
    check-type-assertions: true

  govet:
    # Enable all analyzers
    enable-all: true

  gocyclo:
    # Minimal cyclomatic complexity to report
    min-complexity: 15

  funlen:
    # Maximum function length
    lines: 100
    statements: 50

  goconst:
    # Minimal length of string constant
    min-len: 3
    # Minimum occurrences to trigger
    min-occurrences: 3

  misspell:
    locale: US

  revive:
    # Enables all rules by default
    rules:
      - name: exported
        arguments:
          - "checkPrivateReceivers"
          - "sayRepetitiveInsteadOfStutters"

issues:
  # Maximum issues count per one linter
  max-issues-per-linter: 0

  # Maximum count of issues with the same text
  max-same-issues: 0

  # Exclude some linters from running on tests files
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen
        - gocyclo
        - dupl
